// Code generated by mockery v2.10.0. DO NOT EDIT.

package mocks

import (
	context "context"

	models "github.com/stashapp/stash/pkg/models"
	mock "github.com/stretchr/testify/mock"
)

// ExternalIDReaderWriter is an autogenerated mock type for the ExternalIDReaderWriter type
type ExternalIDReaderWriter struct {
	mock.Mock
}

// AllSources provides a mock function with given fields: ctx
func (_m *ExternalIDReaderWriter) AllSources(ctx context.Context) ([]*models.ExternalSource, error) {
	ret := _m.Called(ctx)

	var r0 []*models.ExternalSource
	if rf, ok := ret.Get(0).(func(context.Context) []*models.ExternalSource); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*models.ExternalSource)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// CreateSource provides a mock function with given fields: ctx, input
func (_m *ExternalIDReaderWriter) CreateSource(ctx context.Context, input models.ExternalSourceInput) (*models.ExternalSource, error) {
	ret := _m.Called(ctx, input)

	var r0 *models.ExternalSource
	if rf, ok := ret.Get(0).(func(context.Context, models.ExternalSourceInput) *models.ExternalSource); ok {
		r0 = rf(ctx, input)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.ExternalSource)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, models.ExternalSourceInput) error); ok {
		r1 = rf(ctx, input)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// DestroyForEntity provides a mock function with given fields: ctx, entityType, entityID
func (_m *ExternalIDReaderWriter) DestroyForEntity(ctx context.Context, entityType string, entityID int) error {
	ret := _m.Called(ctx, entityType, entityID)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, int) error); ok {
		r0 = rf(ctx, entityType, entityID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// FindByEntity provides a mock function with given fields: ctx, entityType, entityID
func (_m *ExternalIDReaderWriter) FindByEntity(ctx context.Context, entityType string, entityID int) ([]*models.ExternalID, error) {
	ret := _m.Called(ctx, entityType, entityID)

	var r0 []*models.ExternalID
	if rf, ok := ret.Get(0).(func(context.Context, string, int) []*models.ExternalID); ok {
		r0 = rf(ctx, entityType, entityID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*models.ExternalID)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, string, int) error); ok {
		r1 = rf(ctx, entityType, entityID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FindByExternalID provides a mock function with given fields: ctx, sourceID, externalID
func (_m *ExternalIDReaderWriter) FindByExternalID(ctx context.Context, sourceID int, externalID string) ([]*models.ExternalID, error) {
	ret := _m.Called(ctx, sourceID, externalID)

	var r0 []*models.ExternalID
	if rf, ok := ret.Get(0).(func(context.Context, int, string) []*models.ExternalID); ok {
		r0 = rf(ctx, sourceID, externalID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*models.ExternalID)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, int, string) error); ok {
		r1 = rf(ctx, sourceID, externalID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FindByID provides a mock function with given fields: ctx, id
func (_m *ExternalIDReaderWriter) FindByID(ctx context.Context, id int) (*models.ExternalID, error) {
	ret := _m.Called(ctx, id)

	var r0 *models.ExternalID
	if rf, ok := ret.Get(0).(func(context.Context, int) *models.ExternalID); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.ExternalID)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, int) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FindSourceByName provides a mock function with given fields: ctx, name
func (_m *ExternalIDReaderWriter) FindSourceByName(ctx context.Context, name string) (*models.ExternalSource, error) {
	ret := _m.Called(ctx, name)

	var r0 *models.ExternalSource
	if rf, ok := ret.Get(0).(func(context.Context, string) *models.ExternalSource); ok {
		r0 = rf(ctx, name)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.ExternalSource)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, name)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Record provides a mock function with given fields: ctx, input
func (_m *ExternalIDReaderWriter) Record(ctx context.Context, input models.ExternalIDInput) (*models.ExternalID, error) {
	ret := _m.Called(ctx, input)

	var r0 *models.ExternalID
	if rf, ok := ret.Get(0).(func(context.Context, models.ExternalIDInput) *models.ExternalID); ok {
		r0 = rf(ctx, input)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.ExternalID)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, models.ExternalIDInput) error); ok {
		r1 = rf(ctx, input)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// SweepOrphans provides a mock function with given fields: ctx
func (_m *ExternalIDReaderWriter) SweepOrphans(ctx context.Context) (int, error) {
	ret := _m.Called(ctx)

	var r0 int
	if rf, ok := ret.Get(0).(func(context.Context) int); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Get(0).(int)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
