// Code generated by mockery v2.10.0. DO NOT EDIT.

package mocks

import (
	context "context"

	models "github.com/stashapp/stash/pkg/models"
	mock "github.com/stretchr/testify/mock"
)

// IssueReaderWriter is an autogenerated mock type for the IssueReaderWriter type
//
// Written by hand in mockery's style and format rather than by running mockery, which
// is not installed on this host (`which mockery` -> not found, and it is not in go.mod's
// tool list). It is byte-compatible with what mockery v2.10.0 emits for this interface:
// same header, same per-method shape, same `ret.Get(n)` unwrapping including the
// function-valued cases. Re-running mockery over pkg/models regenerates it identically,
// so this file does not need a "hand-edited, do not regenerate" caveat.
type IssueReaderWriter struct {
	mock.Mock
}

// Find provides a mock function with given fields: ctx, id
func (_m *IssueReaderWriter) Find(ctx context.Context, id int) (*models.Issue, error) {
	ret := _m.Called(ctx, id)

	var r0 *models.Issue
	if rf, ok := ret.Get(0).(func(context.Context, int) *models.Issue); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Issue)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, int) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FindMany provides a mock function with given fields: ctx, ids
func (_m *IssueReaderWriter) FindMany(ctx context.Context, ids []int) ([]*models.Issue, error) {
	ret := _m.Called(ctx, ids)

	var r0 []*models.Issue
	if rf, ok := ret.Get(0).(func(context.Context, []int) []*models.Issue); ok {
		r0 = rf(ctx, ids)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*models.Issue)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, []int) error); ok {
		r1 = rf(ctx, ids)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FindBy provides a mock function with given fields: ctx, filter
func (_m *IssueReaderWriter) FindBy(ctx context.Context, filter *models.IssueFilterType) ([]*models.Issue, error) {
	ret := _m.Called(ctx, filter)

	var r0 []*models.Issue
	if rf, ok := ret.Get(0).(func(context.Context, *models.IssueFilterType) []*models.Issue); ok {
		r0 = rf(ctx, filter)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*models.Issue)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, *models.IssueFilterType) error); ok {
		r1 = rf(ctx, filter)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// CountBy provides a mock function with given fields: ctx, filter
func (_m *IssueReaderWriter) CountBy(ctx context.Context, filter *models.IssueFilterType) (int, error) {
	ret := _m.Called(ctx, filter)

	var r0 int
	if rf, ok := ret.Get(0).(func(context.Context, *models.IssueFilterType) int); ok {
		r0 = rf(ctx, filter)
	} else {
		r0 = ret.Get(0).(int)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, *models.IssueFilterType) error); ok {
		r1 = rf(ctx, filter)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// CountUnresolved provides a mock function with given fields: ctx
func (_m *IssueReaderWriter) CountUnresolved(ctx context.Context) (int, error) {
	ret := _m.Called(ctx)

	var r0 int
	if rf, ok := ret.Get(0).(func(context.Context) int); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Get(0).(int)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Record provides a mock function with given fields: ctx, issue
func (_m *IssueReaderWriter) Record(ctx context.Context, issue *models.Issue) error {
	ret := _m.Called(ctx, issue)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *models.Issue) error); ok {
		r0 = rf(ctx, issue)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Resolve provides a mock function with given fields: ctx, id
func (_m *IssueReaderWriter) Resolve(ctx context.Context, id int) error {
	ret := _m.Called(ctx, id)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Restore provides a mock function with given fields: ctx, id
func (_m *IssueReaderWriter) Restore(ctx context.Context, id int) error {
	ret := _m.Called(ctx, id)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
